/**
 * QABot Configuration Template
 * Generated by: qabot init
 * Documentation: https://github.com/geargames/qabot
 */
export default {
  project: {
    name: '{{projectName}}',
    type: '{{projectType}}',
  },

  environments: {
    {{#each environments}}
    {{@key}}: {
      url: '{{this.url}}',
      {{#if this.vpn}}vpn: true,{{/if}}
    },
    {{/each}}
  },

  layers: {
    {{#if layers.unit}}
    unit: {
      runner: '{{layers.unit.runner}}',
      command: '{{layers.unit.command}}',
      testMatch: '{{layers.unit.testMatch}}',
    },
    {{/if}}
    {{#if layers.integration}}
    integration: {
      runner: '{{layers.integration.runner}}',
      command: '{{layers.integration.command}}',
      testMatch: '{{layers.integration.testMatch}}',
    },
    {{/if}}
    {{#if layers.e2e}}
    e2e: {
      runner: '{{layers.e2e.runner}}',
      command: '{{layers.e2e.command}}',
      testDir: '{{layers.e2e.testDir}}',
    },
    {{/if}}
  },

  auth: {
    provider: '{{auth.provider}}',
    credentials: {
      email: '{{auth.credentials.email}}',
      password: '{{auth.credentials.password}}',
    },
  },

  features: {
    {{#each features}}
    '{{this.name}}': {
      src: '{{this.src}}',
      priority: '{{this.priority}}',
    },
    {{/each}}
  },

  ai: {
    provider: '{{ai.provider}}',
    model: '{{ai.model}}',
    apiKeyEnv: '{{ai.apiKeyEnv}}',
  },

  useCases: {
    dir: '{{useCases.dir}}',
    formats: ['md', 'feature', 'txt'],
  },

  reporting: {
    outputDir: '{{reporting.outputDir}}',
    openAfterRun: true,
    history: true,
    formats: ['html', 'json'],
  },
};
